dataset:
  traffic:
    url: "https://raw.githubusercontent.com/yungshenglu/USTC-TFC2016/master"
    classes:
      Benign:
        - name: "Skype"
          extension: ".pcap"
        - name: "MySQL"
          extension: ".pcap"
        - name: "BitTorrent"
          extension: ".pcap"
        - name: "Facetime"
          extension: ".pcap"
        - name: "Weibo"
          extension: ".7z"
      Malware:
        - name: "Zeus"
          extension: ".pcap"
        - name: "Tinba"
          extension: ".pcap"
        - name: "Cridex"
          extension: ".7z"
        - name: "Geodo"
          extension: ".7z"
        - name: "Miuref"
          extension: ".pcap"
        
user:
  name: "pramitde726"
  repo: "Optimized-TrafficCLIP-Edge"
  ht_repo: "Optimized-TrafficCLIP-Edge-tuning"

# prompts:
#   BitTorrent : "Sparse but highly concurrent network flow with massive peer-to-peer connection establishment and aggressive packet-size distribution for distributed data chunk retrieval."
#   Cridex: "High-entropy HTTPS traffic with periodic beaconing and bursty command-and-control synchronization, characterized by small outbound packets and large encrypted payload updates."
#   Gmail : "High-volume TLS traffic with variable throughput and large packet length variance, typical of browser-based webmail synchronization and interactive session updates."
#   Skype : "Constant-bitrate UDP streaming with low jitter and symmetric flow distribution, representing real-time peer-to-peer encrypted media communication and synchronization."
#   Tinba : "Compact, low-latency UDP-like behavior over TCP, exhibiting frequent polling with very small packet sizes and highly consistent inter-arrival times for lightweight synchronization."
#   Zeus  : "Persistent TCP connection with low throughput and irregular bursts, showing botnet communication patterns and fragmented data exfiltration via non-standard HTTP headers."

paths:
  raw_data_dir: "data/raw/"
  mini_output_data_file: "data/processed/traffic_dataset_metadata_mini.npz"
  output_data_file: "data/processed/traffic_dataset_metadata.npz"
  tensors_dir: "data/tensors/"

preprocess:
  batch_size: 64
  tokenizer: "google-bert/bert-base-uncased"
  max_length: 64
  
train:
  seed : 42
  tuning_epochs : 8
  original:
    batch_size: 64
    epochs: 100 # 100
    # lambda_cl : 1.0
  optimized:
    batch_size: 64
    epochs: 100 # 100
    # lambda_cl : 2.0
  
early_stopping:
  original:
    patience: 10
    delta: 0.01
  optimized:
    patience: 10
    delta: 0.01
  

test:
  seed: 42
  max_length: 64
  batch_size: 64